export const CLOSE_AUTH_MODAL = "CLOSE_AUTH_MODAL";
export const OPEN_AUTH_MODAL = "OPEN_AUTH_MODAL";
export const CHANGE_AUTH_PAGE = "CHANGE_AUTH_PAGE";


export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";
export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST";

export const GET_SERVICE_INPUTS_SUCCESS = "GET_SERVICE_INPUTS_SUCCESS";
export const GET_SERVICE_INPUTS_FAILURE = "GET_SERVICE_INPUTS_FAILURE";
export const GET_SERVICE_INPUTS_REQUEST = "GET_SERVICE_INPUTS_REQUEST";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CLEAN_TEMP_BOOKING_ID = "CLEAN_TEMP_BOOKING_ID";
export const CREATE_BOOKING_FAILURE = "CREATE_BOOKING_FAILURE";
export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_PAYMENT_INTENT_REQUEST = "CREATE_PAYMENT_INTENT_REQUEST";
export const CREATE_PAYMENT_INTENT_SUCCESS = "CREATE_PAYMENT_INTENT_SUCCESS";
export const CREATE_PAYMENT_INTENT_FAILURE = "CREATE_PAYMENT_INTENT_FAILURE";


export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAILURE = "GET_BOOKINGS_FAILURE";
export const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST";

export const VALIDATE_BOOKING_SUCCESS = "VALIDATE_BOOKINGS_SUCCESS";
export const VALIDATE_BOOKING_FAILURE = "VALIDATE_BOOKING_FAILURE";
export const VALIDATE_BOOKING_REQUEST = "VALIDATE_BOOKING_REQUEST";

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";

export const BOOKING_INFORMATION_RECORDED = "BOOKING_INFORMATION_RECORDED";

export const SET_CURRENT_STEP = "SET_CURRENT_STEP";

export const SET_CART_TYPE = "SET_CART_TYPE";
export const DELETE_BOOKING_INFO = "DELETE_BOOKING_INFO";

export const SET_ERROR_MSG = "SET_ERROR_MSG"
export const CLEAN_ERROR_MSG = "CLEAN_ERROR_MSG"

export const GET_TIMESLOT_REQUEST = "GET_TIMESLOT_REQUEST";
export const GET_TIMESLOT_SUCCESS = "GET_TIMESLOT_SUCCESS";
export const GET_TIMESLOT_FAILURE = "GET_TIMESLOT_FAILURE";
export const DELETE_TIMESLOTS ="DELETE_TIMESLOTS";

export const CLAIM_TIME_SLOTS_REQUEST = "CLAIM_TIME_SLOTS_REQUEST";
export const CLAIM_TIME_SLOTS_SUCCESS = "CLAIM_TIME_SLOTS_SUCCESS";
export const CLAIM_TIME_SLOTS_FAILURE = "CLAIM_TIME_SLOTS_FAILURE";

export const CLEAN_TIME_SLOTS_STATE = "CLEAN_TIME_SLOTS_STATE";

export const GET_ADMIN_BOOKING_SUCCESS = "GET_ADMIN_BOOKING_SUCCESS";
export const GET_ADMIN_BOOKING_FAILURE = "GET_ADMIN_BOOKING_FAILURE";
export const GET_ADMIN_BOOKING_REQUEST= "GET_ADMIN_BOOKING_REQUEST";


export const GET_ADMIN_TIMESLOT_REQUEST = "GET_ADMIN_TIMESLOT_REQUEST";
export const GET_ADMIN_TIMESLOT_SUCCESS = "GET_ADMIN_TIMESLOT_SUCCESS";
export const GET_ADMIN_TIMESLOT_FAILURE= "GET_ADMIN_TIMESLOT_FAILURE";

export const SWITCH_ADMIN_TIMESLOT_REQUEST = "SWITCH_ADMIN_TIMESLOT_REQUEST";
export const SWITCH_ADMIN_TIMESLOT_FAILURE = "SWITCH_ADMIN_TIMESLOT_FAILURE";
export const SWITCH_ADMIN_TIMESLOT_SUCCESS = "SWITCH_ADMIN_TIMESLOT_SUCCESS";

export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_FAILURE = "GET_PAYMENT_FAILURE";

export const SET_TIME_VALUES = "SET_TIME_VALUES";
export const SET_LOADING= "SET_LOADING";
export const VALIDATE_POSTCODE_FAILURE ="VALIDATE_POSTCODE_FAILURE";
export const VALIDATE_POSTCODE_REQUEST="VALIDATE_POSTCODE_REQUEST";
export const VALIDATE_POSTCODE_SUCCESS="VALIDATE_POSTCODE_SUCCESS";
// export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
// export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";
// export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST";